apiVersion: v1
kind: Service
metadata:
  name: filestoreapp
spec:
  selector:
    app: filestoreapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
  

  
